### ISSUE TITLE
Hard/Impossible to read key-bindings when using dark theme

### ISSUE THREAD

**Issue by Skgland** [melfkammholz/aoc-submissions#22]
Screenshot:
![image](https://user-images.githubusercontent.com/3877590/206285597-fb88f6ec-c367-4e7a-b577-1c98290dfb91.png)

Photo of Screen:
![IMG_20221207_211244](https://user-images.githubusercontent.com/3877590/206286252-9314404e-afe9-4b9e-9d38-264d0633aa56.jpg)

**Comment by xtay2** [comment]
Ebenfalls gefixt in #20
