### ISSUE TITLE
Switching between part A & B switches to the first user in the list

### ISSUE THREAD

**Issue by Skgland** [melfkammholz/aoc-submissions#38]
When I click on `A` or `B` to visit the solution of the corresponding part the user selection changes to the first user of the currently selected day.

Note that the highlighted user does not change, but the url and the displayed solution.

https://github.com/melfkammholz/aoc-submissions/assets/3877590/3cd8f483-27a8-43a6-bc75-55d68bac8670

**Comment by melfkammholz** [comment]
Thanks for pointing that out. I just stumbled on the same issue, should be fixed. Do you mind checking if it works now?

**Comment by Skgland** [comment]
After forcing my browser to clear the cache it appears to be working now :+1:
